apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-storage-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: server-storage
  local:
    path: /mnt/cass-operator/pv000
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - crc-gm7cm-master-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-storage-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: server-storage
  local:
    path: /mnt/cass-operator/pv001
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - crc-gm7cm-master-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-storage-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: server-storage
  local:
    path: /mnt/cass-operator/pv002
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - crc-gm7cm-master-0
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: server-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
